name: Deploy React App to GoDaddy

on:
  push:
    branches:
      - main # or your deploy branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Debug step to ensure the FTP server value is present (will not print the secret)
      - name: Check FTP_SERVER variable
        run: |
          if [[ -z "${{ secrets.FTP_SERVER }}" ]]; then
            echo "FTP_SERVER is empty or missing"
            exit 1
          else
            echo "FTP_SERVER is present"
          fi

      - name: Deploy to GoDaddy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/
